apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herald
resources:
  - ../../base
components:
  - ../../components/postgresql
images:
  - name: quay.io/rarguello/herald
    newTag: dev
